### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by Haeri** [mp-access/Backend#202]
Some sort of breadcrumbs would be helpful as once inside an exercise there is no way of going back op the navigation without directly jumping to home

**Comment by a-a-hofmann** [comment]
What do you need from the backend for this?
I'd like to get this done finally 😄

**Comment by Haeri** [comment]
I think th best aproach would be to provide an array of breadcrumbs with the following routs:
- courses/{id}
- courses/{id}/assignments{id}
- exercises/{id}

A breadcrumb would looks something like this:
```json
"breadcrumbs": [
    {
        "title": "Informatics 1",
        "route": "courses/034d9e52-e0d1-3a94-a39a-457191a4e129"
    },
    {
        "title": "Conditional and Iterative Statements",
        "route": "courses/034d9e52-e0d1-3a94-a39a-457191a4e129/assignments/a3f586fa-fbd6-3620-a1bf-c19e1471cec2"
    }
]
```
So maybe we can create a HasBreadcrumbs.java Interface and Course.java, Assignment.java and Exercise.java would implement it.

But the backend is not the main problem. We have to somehow have a global breadcrumbs variable where we store the current breadcrumbs that we got from the backend and display it in the header.
Apparenlty there is a way to have global variables without having to emply Redux.
