### ISSUE TITLE
CodeSnippet does not execute testsuite

### ISSUE THREAD

**Issue by Haeri** [mp-access/Backend#252]
CodeSnippet workspace only sends one file

**Comment by a-a-hofmann** [comment]
In CodeSnippetExercise, we take only the first file from the public files to show. So when we send publicFiles back on submission, this contains only a single file
https://github.com/mp-access/frontend/blob/cd9c20540a713496a49f1d15b6af0d6c6e1b4d4c/src/components/exercise/CodeSnippetExercise.js#L17-L25

**Comment by a-a-hofmann** [comment]
Btw by doing this, we don't actually have any guarantees that the first file is the actual exercise script.

**Comment by a-a-hofmann** [comment]
I think we should simply add to the config.json of a codeSnippet the filename of the "main" script and then in the frontend we can always be sure which file to show. Then from the frontend send all publicFiles on submission

**Comment by a-a-hofmann** [comment]
Moved this to Post Go-Live as this should be fixed as soon as possible
