### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by Haeri** [mp-access/Backend#253]
- [x] Rename Repositories
- [x] Delete old repositories 
- [x] Introduce Backend Versioning
- [x] Introduce Frontend Versioning
- [x] Introduce Dev branch and Lock master for Backend
- [x] Introduce Dev branch and Lock master for Frontend
- [x] Setup CI for Dev to DO for Backend
- [x] Setup CI for Dev to DO for Frontend

**Comment by a-a-hofmann** [comment]
Where do we want to print the versions?
Are these just hardcoded strings?

**Comment by Haeri** [comment]
Maybe we can get the version for th ebackend from gradle and for the frontend from package.json
I was thinking about putting both versions on the bottom right in the footer of the frontend.

**Comment by a-a-hofmann** [comment]
Would the version be the commit hash & branch or a simple version string (v0.9, v1.0, etc.)?
Should the backend return this from an API?
We could maybe also use it to check if the backend is up and running.

**Comment by a-a-hofmann** [comment]
GET /api/info (no auth needed) returns an object in this form
```
offsetDateTime: "2019-10-12T00:50:11.679909+02:00"
utcTime: "2019-10-11T22:50:11.679940Z"
version: "beta"
zoneId: "Europe/Zurich"
```

On prod version would read v0.10.0 or something like this depending on the configured environment variable
