### ISSUE TITLE
State machine repository cleanup

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Backend#314]
The state machine repository is backed by a in-memory map.
As the state machines are never removed, this map will grow indefinitely which in extreme cases might cause an OoM and crash the server.

The easy solution might be to remove the submission in `getEvalProcessState` once we return to the user that the state machine is done.
https://github.com/mp-access/Backend/blob/806ee0139c40fcb4a0d8ee3a3173c40f15168caa/src/main/java/ch/uzh/ifi/access/student/evaluation/EvalProcessService.java#L51-L65

However what do we do in case the user did not wait for the submission to finish but refreshed, changed exercise, or the submission timed out on the frontend?
In those cases `getEvalProcessState` will not be called.

**Comment by mech-studi** [comment]
Habe deinen Kommentar nicht gesehen. Werde es mir anschauen

**Comment by a-a-hofmann** [comment]
An initial fix is here and is already in the RC branch
https://github.com/mp-access/Backend/pull/342
