### ISSUE TITLE
User Acceptance Environment

### ISSUE THREAD

**Issue by mech-studi** [mp-access/Backend#321]
For our new release procedure we want a new user acceptance environment on digital ocean.
- We have a release candidate branch that is deployed on digital ocean.
- RC feature freeze is on Wednesday an is testes one week until the release one week later.

**Comment by a-a-hofmann** [comment]
Are we talking about another environment or the existing one?

How does this work now?

- Everything we develop until next wednesday is auto deployed to digital ocean
- On wednesday is feature freeze and auto-deployment is halted.
- In the meantime we continue developing new features on a second RC branch and test the "old" RC branch on DO
- On the second wednesday we release the first RC branch to production and push the second RC. branch to DO for testing. We then open a third RC branch and continue like this?

Did I get this correctly? 😅
