### ISSUE TITLE
Additional Group Permission for Admins

### ISSUE THREAD

**Issue by mech-studi** [mp-access/Backend#326]

**Comment by mech-studi** [comment]
GrantedCourseAccess muss ich wohl auch noch anpassen?

**Comment by mech-studi** [comment]
Hätte noch eine andere idee gehabt, wäre es nicht einfacher anstatt ein Objekt: 
GrantedCourseAccess(<course-name>,  isStudent, isAssistant, isAdmin)

einfach mehrere Objekte zu erstellen: 
GrantedCourseAccess(<course-name>, <role-name>)

und dann würde im CoursePermissionEvaluator eine methode wie hasGrantedAccess(CourseAuthentication, <role-name>) genügen und wir müssen nicht so viel programmieren wenn etwas am Berechtigungsmodell ändert.

Sorry für den langen Kommentar

**Comment by a-a-hofmann** [comment]
Habe nicht ganz verstanden wie du es machen willst aber kannst gerne machen 👍 
Als ich es geschrieben habe, hab ich nicht wirklich gedacht dass es noch anderen rollen geben werde
