### ISSUE TITLE
Re-Evaluated Submissions dont Affect Submission Counter

### ISSUE THREAD

**Issue by mech-studi** [mp-access/Backend#327]

**Comment by a-a-hofmann** [comment]
This should already be covered by: https://github.com/mp-access/Backend/commit/cda467b2cf9c8516e16ef476484a86e79fc3f1a2

Specifically here
https://github.com/mp-access/Backend/blob/71bec0912fba335a1c469973c8b237f515376e8b/src/main/java/ch/uzh/ifi/access/student/dao/StudentSubmissionRepository.java#L10-L17

**Comment by mech-studi** [comment]
wunderbar. dann schliessen wir es gleich wieder XD
