### ISSUE TITLE
Frontend should correctly nest folder

### ISSUE THREAD

**Issue by a-a-hofmann** [mp-access/Backend#374]
The UI shows all files in the file explorer under public/, private/, ... as flat.
We should show them nested as needed and make sure the task download correctly rebuilds the hierarchy

**Comment by Haeri** [comment]
@a-a-hofmann  I am almost done with this but I'm getting errors about the component not updating correctly. Can you take a look at it?
https://github.com/mp-access/Frontend/commits/fix/nested-folders

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in CodeSnippetExercise (at Exercise.js:294)`

**Comment by a-a-hofmann** [comment]
When does this happen?
I cannot reproduce this

**Comment by Haeri** [comment]
When switching the exercises it sometimes happens but not consistenlty
